<?php

use AgenticActions\TypeScript\Emitter;
use Illuminate\Routing\RouteCollection;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use Tests\Feature\TypeScript\Fixtures\ArchivePost;
use Tests\Feature\TypeScript\Fixtures\CreatePost;
use Tests\Feature\TypeScript\Fixtures\EvalAction;
use Tests\Feature\TypeScript\Fixtures\EveryShape;
use Tests\Fixtures\Actions\CreateNote;
use Tests\Fixtures\Actions\ListNotes;
use Tests\Fixtures\Actions\TeamNote;

it('writes the golden file exactly for CreatePost mounted on the web and api. groups', function () {
    $this->mountRoutes(function (): void {
        // The api mount is registered first, so the web mount wins by its middleware, not by its order.
        Route::middleware(['api', 'auth:sanctum'])->prefix('api/actions')->name('api.actions.')
            ->group(fn () => $this->generatedRoute(CreatePost::class));
        Route::middleware(['web', 'auth'])->prefix('actions')->name('actions.')
            ->group(fn () => $this->generatedRoute(CreatePost::class));
    });

    $file = app(Emitter::class)->render();

    expect($file)->toBe(file_get_contents(__DIR__.'/__snapshots__/create-post.ts'))
        ->and($file)->not->toContain('/api/actions/create-post');
});

it('stamps the version Packages reports, without a leading v', function () {
    $this->mountRoutes(fn () => $this->generatedRoute(CreatePost::class));

    expect(app(Emitter::class)->render())->toStartWith('// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.');

    $this->usePackages(['agentic-actions/laravel' => 'v0.1.0']);

    expect(app(Emitter::class)->render())->toStartWith('// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.');

    $this->usePackages(['agentic-actions/laravel' => 'v0.2.3']);

    expect(app(Emitter::class)->render())->toContain('from agentic-actions/laravel 0.2.3. Do not edit.');
});

it('stamps dev when the version is unknown', function () {
    $this->mountRoutes(fn () => $this->generatedRoute(CreatePost::class));
    $this->usePackages(['agentic-actions/laravel' => '']);

    expect(app(Emitter::class)->render())->toContain('from agentic-actions/laravel dev. Do not edit.');
});

it('takes route parameters out of the input and fills them with uri()', function () {
    $this->mountRoutes(function (): void {
        Route::middleware('web')->prefix('teams/{team}/actions')->name('teams.actions.')
            ->group(fn () => $this->generatedRoute(TeamNote::class));
        Route::post('posts/{post}/archive', ArchivePost::class)->name('posts.archive');
    });

    $file = app(Emitter::class)->render();

    expect($file)
        ->toContain("import { action, uri, type ActionDefinition } from '@agentic-actions/client';")
        ->toContain(<<<'TS'
            export type TeamNoteParams = { team: string | number };

            export type TeamNoteInput = {
                title: string;
            };

            export type TeamNoteOutput = Record<string, never>;

            /** Create a note in the current team. */
            export const teamNote = (params: TeamNoteParams): ActionDefinition<TeamNoteInput, TeamNoteOutput> =>
                action({ name: 'team-note', method: 'post', url: uri('/teams/{team}/actions/team-note', params), touches: [] });
            TS)
        ->toContain(<<<'TS'
            export type ArchivePostParams = { post: string | number };

            export type ArchivePostInput = {
                reason?: string;
            };
            TS)
        ->toContain("url: uri('/posts/{post}/archive', params)");
});

it('marks an optional route parameter optional', function () {
    $this->mountRoutes(fn () => Route::post('posts/{post}/archive/{mode?}', ArchivePost::class)->name('posts.archive'));

    expect(app(Emitter::class)->render())
        ->toContain('export type ArchivePostParams = { post: string | number; mode?: string | number };')
        ->toContain("url: uri('/posts/{post}/archive/{mode?}', params)");
});

it('maps every schema shape, an empty input and output as Record<string, never>, with Json declared once', function () {
    $this->mountRoutes(function (): void {
        $this->generatedRoute(EveryShape::class);
        $this->generatedRoute(CreateNote::class);
        $this->generatedRoute(ListNotes::class);
    });

    $file = app(Emitter::class)->render();

    expect($file)
        ->toStartWith(<<<'TS'
            // Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.
            import { action, type ActionDefinition } from '@agentic-actions/client';

            type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

            export type CreateNoteInput = {
            TS)
        ->toContain(<<<'TS'
            export type EveryShapeInput = {
                status: 'draft' | 'published';
                priority: 1 | 2 | 3;
                ratio?: number;
                flag: boolean;
                tags: Array<string>;
                labels?: Array<'a' | 'b'>;
                anything?: Array<Json>;
                meta?: Record<string, Json>;
                author: {
                    /** As printed on the byline. */
                    name: string;
                    email?: string | null;
                };
                lines?: Array<{
                    sku: string;
                    qty?: number;
                }>;
                attachment?: File | Blob;
                'content-type'?: string;
                note: string | null;
            };
            TS)
        ->toContain(<<<'TS'
            /** Every schema shape the emitter maps. It keeps *\/ inside the comment. */
            export const everyShape = (): ActionDefinition<EveryShapeInput, EveryShapeOutput> =>
                action({ name: 'every-shape', method: 'post', url: '/every-shape', touches: ['shapes', 'it\'s'] });
            TS)
        ->toContain('export type EveryShapeOutput = Record<string, never>;')
        ->toContain('export type ListNotesInput = Record<string, never>;')
        ->toContain(<<<'TS'
            export type ListNotesOutput = {
                posts: Array<{
                    id: number;
                    title: string;
                }>;
            };
            TS)
        ->and(substr_count($file, 'type Json ='))->toBe(1)
        ->and($file)->not->toMatch('/\\bany\\b|\\bunknown\\b/');
});

it('takes the first generated route when none is in the web group', function () {
    $this->mountRoutes(function (): void {
        Route::prefix('internal')->name('internal.')->group(fn () => $this->generatedRoute(CreateNote::class));
        Route::middleware('api')->prefix('api')->name('api.')->group(fn () => $this->generatedRoute(CreateNote::class));
    });

    expect(app(Emitter::class)->render())
        ->toContain("url: '/internal/create-note'")
        ->not->toContain('/api/create-note');
});

it('exports named hand-written routes as extras, by route name', function () {
    $this->mountRoutes(function (): void {
        Route::middleware('web')->group(function (): void {
            Route::post('notes/unnamed', CreateNote::class);
            $this->generatedRoute(CreateNote::class);
            Route::post('notes', CreateNote::class)->name('notes.store');
        });
        Route::post('posts/{post}/archive', ArchivePost::class)->name('posts.archive');
        Route::post('api/posts/{post}/archive', ArchivePost::class)->name('api.posts.archive');
    });

    $file = app(Emitter::class)->render();

    expect($file)
        ->toContain(<<<'TS'
            /** Create a note for the signed-in author. */
            export const createNote = (): ActionDefinition<CreateNoteInput, CreateNoteOutput> =>
                action({ name: 'create-note', method: 'post', url: '/create-note', touches: [] });
            TS)
        ->toContain(<<<'TS'
            /** Create a note for the signed-in author. */
            export const notesStore = (): ActionDefinition<NotesStoreInput, NotesStoreOutput> =>
                action({ name: 'create-note', method: 'post', url: '/notes', touches: [] });
            TS)
        ->toContain("export const archivePost = (params: ArchivePostParams): ActionDefinition<ArchivePostInput, ArchivePostOutput> =>\n    action({ name: 'archive-post', method: 'post', url: uri('/posts/{post}/archive', params), touches: [] });")
        ->toContain("export const apiPostsArchive = (params: ApiPostsArchiveParams): ActionDefinition<ApiPostsArchiveInput, ApiPostsArchiveOutput> =>\n    action({ name: 'archive-post', method: 'post', url: uri('/api/posts/{post}/archive', params), touches: [] });")
        ->not->toContain('notes/unnamed');

    // In action-name order, each primary before its extras.
    expect(strpos($file, 'export const apiPostsArchive'))->toBeGreaterThan(strpos($file, 'export const archivePost'))
        ->and(strpos($file, 'export const createNote'))->toBeGreaterThan(strpos($file, 'export const apiPostsArchive'))
        ->and(strpos($file, 'export const notesStore'))->toBeGreaterThan(strpos($file, 'export const createNote'));
});

it('skips routes that do not accept POST or do not reach an action', function () {
    $this->mountRoutes(function (): void {
        Route::get('notes', CreateNote::class)->name('notes.index');
        Route::post('closure', fn () => 'ok')->name('closure');
    });

    expect(app(Emitter::class)->render())
        ->toBe("// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.\nexport {};\n");
});

it('renders the same text twice, whatever order the routes were registered in', function () {
    $mount = function (array $classes): string {
        Route::setRoutes(new RouteCollection);

        $this->mountRoutes(function () use ($classes): void {
            foreach ($classes as $class) {
                $this->generatedRoute($class);
            }
        });

        return app(Emitter::class)->render();
    };

    $first = $mount([CreateNote::class, ListNotes::class, EveryShape::class]);

    expect($mount([EveryShape::class, ListNotes::class, CreateNote::class]))->toBe($first)
        ->and(app(Emitter::class)->render())->toBe($first);
});

it('refuses an export name TypeScript cannot use, strict mode\'s included', function (?string $route, string $message) {
    $this->mountRoutes(function () use ($route): void {
        if ($route === null) {
            $this->generatedRoute(EvalAction::class);

            return;
        }

        Route::post('notes', CreateNote::class)->name('notes.store');
        Route::post('notes/extra', CreateNote::class)->name($route);
    });

    expect(fn () => app(Emitter::class)->render())->toThrow(LogicException::class, $message);
})->with([
    'a reserved word' => ['delete', 'The route [delete] cannot be exported to TypeScript as [delete]. Give it another name.'],
    'the route eval' => ['eval', 'The route [eval] cannot be exported to TypeScript as [eval]. Give it another name.'],
    'the route arguments' => ['arguments', 'The route [arguments] cannot be exported to TypeScript as [arguments]. Give it another name.'],
    'the action eval' => [null, 'The action [eval] cannot be exported to TypeScript as [eval]. Give it another name.'],
]);

it('refuses two exports with one name', function () {
    $this->mountRoutes(function (): void {
        $this->generatedRoute(CreateNote::class);
        Route::post('notes', CreateNote::class)->name('create-note');
    });

    app(Emitter::class)->render();
})->throws(LogicException::class, 'The route [create-note] is exported to TypeScript as [createNote], a name the action [create-note] already takes.');

it('resolves the configured path against the base path unless it is absolute', function () {
    expect(app(Emitter::class)->path())->toBe(base_path('resources/js/agentic/actions.ts'));

    config(['agentic-actions.typescript.path' => '/tmp/agentic/actions.ts']);

    expect(app(Emitter::class)->path())->toBe('/tmp/agentic/actions.ts');
});

it('writes js/tests/fixtures/actions.ts from the fixture routes, and fails when the committed copy is stale', function () {
    $this->mountRoutes(function (): void {
        Route::middleware(['api', 'auth:sanctum'])->prefix('api/actions')->name('api.actions.')
            ->group(fn () => $this->generatedRoute(CreateNote::class));

        Route::middleware(['web', 'auth'])->prefix('actions')->name('actions.')->group(function (): void {
            $this->generatedRoute(CreateNote::class);
            $this->generatedRoute(ListNotes::class);
            $this->generatedRoute(EveryShape::class);
        });

        Route::middleware(['web', 'auth'])->prefix('teams/{team}/actions')->name('teams.actions.')
            ->group(fn () => $this->generatedRoute(TeamNote::class));

        Route::middleware(['web', 'auth'])->group(function (): void {
            Route::post('posts/{post}/archive', ArchivePost::class)->name('posts.archive');
            Route::post('api/posts/{post}/archive/{mode?}', ArchivePost::class)->name('api.posts.archive');
        });
    });

    $path = dirname(__DIR__, 3).'/js/tests/fixtures/actions.ts';
    $rendered = app(Emitter::class)->render();
    $committed = is_file($path) ? file_get_contents($path) : null;

    if ($committed !== $rendered) {
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $rendered);
    }

    expect($committed)->toBe($rendered, 'js/tests/fixtures/actions.ts was stale and has been rewritten: run npm --prefix js run test:types, then commit it.');
});
