<?php

namespace AgenticActions\TypeScript;

use AgenticActions\Action;
use AgenticActions\Exposure\ClassExposure;
use AgenticActions\Exposure\Entry;
use AgenticActions\Schema\SchemaReader;
use AgenticActions\Support\Packages;
use AgenticActions\Support\Paths;
use Illuminate\Routing\Route;
use Illuminate\Support\Str;
use LogicException;

/**
 * Writes resources/js/agentic/actions.ts: one typed definition per action route. The file imports only the npm
 * root and depends on nothing but the routes and the schemas, so --check is stable.
 *
 * @internal
 */
final class Emitter
{
    use Literals;

    /**
     * Words an export may not take: JavaScript's reserved words, eval and arguments, which a module's strict mode
     * never lets a declaration take, and the names the file imports.
     */
    private const RESERVED = [
        'action', 'uri', 'arguments', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
        'default', 'delete', 'do', 'else', 'enum', 'eval', 'export', 'extends', 'false', 'finally', 'for', 'function',
        'if', 'implements', 'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private',
        'protected', 'public', 'return', 'static', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof',
        'var', 'void', 'while', 'with', 'yield',
    ];

    /**
     * The local type for shapes the schema leaves open.
     */
    private const JSON = 'type Json = string | number | boolean | null | Json[] | { [key: string]: Json };';

    /**
     * Create the emitter.
     */
    public function __construct(
        private readonly RouteSelector $routes,
        private readonly SchemaReader $reader,
        private readonly Packages $packages,
    ) {}

    /**
     * The whole generated file.
     */
    public function render(): string
    {
        $usesJson = false;
        $writer = new TypeWriter(function () use (&$usesJson): void {
            $usesJson = true;
        });

        $usesUri = false;
        $blocks = [];

        foreach ($this->definitions() as $definition) {
            $blocks[] = $this->block($definition, $writer);
            $usesUri = $usesUri || $definition['route']->parameterNames() !== [];
        }

        $version = $this->packages->version('agentic-actions/laravel');
        $header = '// Generated by `php artisan actions:typescript` from agentic-actions/laravel '.($version === null || $version === '' ? 'dev' : $version).'. Do not edit.';

        if ($blocks === []) {
            return $header."\nexport {};\n";
        }

        $import = 'import { '.implode(', ', array_filter(['action', $usesUri ? 'uri' : null, 'type ActionDefinition'])).' } from \'@agentic-actions/client\';';

        return implode("\n\n", [$header."\n".$import, ...($usesJson ? [self::JSON] : []), ...$blocks])."\n";
    }

    /**
     * The resolved output path.
     */
    public function path(): string
    {
        return Paths::resolve((string) config('agentic-actions.typescript.path', 'resources/js/agentic/actions.ts'));
    }

    /**
     * Every exported definition, in action-name order: each action's primary route, then its extras by route name.
     *
     * @return list<array{entry: Entry, route: Route, export: string, prefix: string, extra: bool}>
     */
    private function definitions(): array
    {
        $selection = $this->routes->select();
        $definitions = [];

        foreach ($selection['primary'] as $class => $route) {
            $entry = ClassExposure::of($class);

            $definitions[] = [
                'entry' => $entry,
                'route' => $route,
                'export' => Str::camel($entry->name),
                'prefix' => Str::studly($entry->name),
                'extra' => false,
            ];
        }

        foreach ($selection['extra'] as $name => $route) {
            $class = ltrim((string) $route->getControllerClass(), '\\');

            if (! is_subclass_of($class, Action::class)) {
                continue;
            }

            $base = str_replace('.', '_', $name);

            $definitions[] = [
                'entry' => ClassExposure::of($class),
                'route' => $route,
                'export' => Str::camel($base),
                'prefix' => Str::studly($base),
                'extra' => true,
            ];
        }

        usort($definitions, fn (array $a, array $b): int => [$a['entry']->name, $a['extra'], (string) $a['route']->getName()]
            <=> [$b['entry']->name, $b['extra'], (string) $b['route']->getName()]);

        $taken = [];

        foreach ($definitions as $definition) {
            $export = $definition['export'];
            $source = $definition['extra']
                ? 'The route ['.$definition['route']->getName().']'
                : 'The action ['.$definition['entry']->name.']';

            if (! self::isIdentifier($export) || in_array($export, self::RESERVED, true)) {
                throw new LogicException("{$source} cannot be exported to TypeScript as [{$export}]. Give it another name.");
            }

            if (isset($taken[$export]) || isset($taken[$definition['prefix']])) {
                throw new LogicException("{$source} is exported to TypeScript as [{$export}], a name ".($taken[$export] ?? $taken[$definition['prefix']]).' already takes. Give one of them another name.');
            }

            $taken[$export] = strtolower($source);
            $taken[$definition['prefix']] = strtolower($source);
        }

        return $definitions;
    }

    /**
     * One definition's types and export.
     *
     * @param  array{entry: Entry, route: Route, export: string, prefix: string, extra: bool}  $definition
     */
    private function block(array $definition, TypeWriter $writer): string
    {
        ['entry' => $entry, 'route' => $route, 'export' => $export, 'prefix' => $prefix] = $definition;

        $action = $entry->action();
        $parameters = $route->parameterNames();
        $path = '/'.ltrim($route->uri(), '/');

        $lines = [];

        if ($parameters !== []) {
            $fields = array_map(
                fn (string $name): string => self::key($name).(str_contains($path, '{'.$name.'?}') ? '?' : '').': string | number',
                $parameters,
            );

            $lines[] = "export type {$prefix}Params = { ".implode('; ', $fields).' };';
        }

        $lines[] = "export type {$prefix}Input = ".$writer->object($this->reader->input($action), $parameters).';';
        $lines[] = "export type {$prefix}Output = ".$writer->object($this->reader->output($action)).';';

        $signature = ($parameters === [] ? '()' : "(params: {$prefix}Params)")
            .": ActionDefinition<{$prefix}Input, {$prefix}Output> =>";

        $call = 'action({ name: '.self::quote($entry->name)
            .", method: 'post', url: "
            .($parameters === [] ? self::quote($path) : 'uri('.self::quote($path).', params)')
            .', touches: ['.implode(', ', array_map(self::quote(...), $entry->touches)).'] });';

        $lines[] = ($entry->description !== '' ? self::comment($entry->description)."\n" : '')
            ."export const {$export} = {$signature}\n    {$call}";

        return implode("\n\n", $lines);
    }
}
