// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.
import { action, type ActionDefinition } from '@agentic-actions/client';

export type CreatePostInput = {
    title: string;
    body: string;
    /** One line for listings. Left empty when omitted. */
    excerpt?: string | null;
};

export type CreatePostOutput = {
    id: number;
    title: string;
};

/** Create a draft blog post. Publishing is a separate action. */
export const createPost = (): ActionDefinition<CreatePostInput, CreatePostOutput> =>
    action({ name: 'create-post', method: 'post', url: '/actions/create-post', touches: ['posts'] });
