// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.1.0. Do not edit.
import { action, uri, type ActionDefinition } from '@agentic-actions/client';

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

export type ArchivePostParams = { post: string | number };

export type ArchivePostInput = {
    reason?: string;
};

export type ArchivePostOutput = {
    archived: boolean;
};

/** Archive one of your posts. */
export const archivePost = (params: ArchivePostParams): ActionDefinition<ArchivePostInput, ArchivePostOutput> =>
    action({ name: 'archive-post', method: 'post', url: uri('/posts/{post}/archive', params), touches: [] });

export type ApiPostsArchiveParams = { post: string | number; mode?: string | number };

export type ApiPostsArchiveInput = {
    reason?: string;
};

export type ApiPostsArchiveOutput = {
    archived: boolean;
};

/** Archive one of your posts. */
export const apiPostsArchive = (params: ApiPostsArchiveParams): ActionDefinition<ApiPostsArchiveInput, ApiPostsArchiveOutput> =>
    action({ name: 'archive-post', method: 'post', url: uri('/api/posts/{post}/archive/{mode?}', params), touches: [] });

export type CreateNoteInput = {
    title: string;
    body: string;
    excerpt?: string | null;
};

export type CreateNoteOutput = {
    id: number;
    title: string;
};

/** Create a note for the signed-in author. */
export const createNote = (): ActionDefinition<CreateNoteInput, CreateNoteOutput> =>
    action({ name: 'create-note', method: 'post', url: '/actions/create-note', touches: [] });

export type EveryShapeInput = {
    status: 'draft' | 'published';
    priority: 1 | 2 | 3;
    ratio?: number;
    flag: boolean;
    tags: Array<string>;
    labels?: Array<'a' | 'b'>;
    anything?: Array<Json>;
    meta?: Record<string, Json>;
    author: {
        /** As printed on the byline. */
        name: string;
        email?: string | null;
    };
    lines?: Array<{
        sku: string;
        qty?: number;
    }>;
    attachment?: File | Blob;
    'content-type'?: string;
    note: string | null;
};

export type EveryShapeOutput = Record<string, never>;

/** Every schema shape the emitter maps. It keeps *\/ inside the comment. */
export const everyShape = (): ActionDefinition<EveryShapeInput, EveryShapeOutput> =>
    action({ name: 'every-shape', method: 'post', url: '/actions/every-shape', touches: ['shapes', 'it\'s'] });

export type ListNotesInput = Record<string, never>;

export type ListNotesOutput = {
    posts: Array<{
        id: number;
        title: string;
    }>;
};

/** List the signed-in author's notes. */
export const listNotes = (): ActionDefinition<ListNotesInput, ListNotesOutput> =>
    action({ name: 'list-notes', method: 'post', url: '/actions/list-notes', touches: [] });

export type TeamNoteParams = { team: string | number };

export type TeamNoteInput = {
    title: string;
};

export type TeamNoteOutput = Record<string, never>;

/** Create a note in the current team. */
export const teamNote = (params: TeamNoteParams): ActionDefinition<TeamNoteInput, TeamNoteOutput> =>
    action({ name: 'team-note', method: 'post', url: uri('/teams/{team}/actions/team-note', params), touches: [] });
